### ISSUE TITLE
导出题库之后该如何作答呢

### ISSUE THREAD

**Issue by XXXXBully** [pooneyy/WeibanQuestionsBank#4]
导出题库之后该如何作答呢

**Comment by pooneyy** [comment]
电脑上Ctrl+F搜索题目中的关键词，找到题库中对应的题

**Comment by XXXXBully** [comment]
> 电脑上Ctrl+F搜索题目中的关键词，找到题库中对应的题

就是还无法自动答题，需要手动搜索

**Comment by pooneyy** [comment]
> > 电脑上Ctrl+F搜索题目中的关键词，找到题库中对应的题
> 
> 就是还无法自动答题，需要手动搜索

这个不是自动答题工具，这个是单纯的题库。

**Comment by XXXXBully** [comment]
OK了解谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月4日(周四) 中午11:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pooneyy/WeibanQuestionsBank] 导出题库之后该如何作答呢 (Issue #4)




   
电脑上Ctrl+F搜索题目中的关键词，找到题库中对应的题
  
就是还无法自动答题，需要手动搜索
  
这个不是自动答题工具，这个是单纯的题库。
