### ISSUE TITLE
导出来的答题记录也不知道哪个是正确的啊

### ISSUE THREAD

**Issue by gff1313** [pooneyy/WeibanQuestionsBank#7]

**Comment by pooneyy** [comment]
把导出来的答题记录导入到题库文件里就行了，题库只会记录正确答案

你也可以只提交答题记录，我把它合并到题库里

**Comment by gff1313** [comment]
是导入到importonereviewpaper.py这个文件里看就行了嘛

**Comment by pooneyy** [comment]
是的。记得答题记录的文件名是data.json，否则会报错。或者你不确定怎么弄的话，只提交答题记录也行，剩下的我来做
